language: python
sudo: true

python:
 - 3.5
 - 3.6
 - 3.7

env:
 - DJANGO_VERSION=2.1.11 PGDB=9.6
 - DJANGO_VERSION=2.1.11 PGDB=10
 - DJANGO_VERSION=2.2.4 PGDB=9.6
 - DJANGO_VERSION=2.2.4 PGDB=10

before_install:
  - sudo -E service postgresql stop 9.2
  - sudo -E service postgresql stop 9.3
  - sudo -E service postgresql stop 9.4
  - sudo -E service postgresql stop 9.5
  - sudo -E service postgresql stop 9.6
  - sudo -E apt-get -yq --no-install-suggests --no-install-recommends $(travis_apt_get_options) install postgresql-$PGDB postgresql-client-$PGDB postgresql-$PGDB-postgis-2.4 postgresql-$PGDB-postgis-2.4-scripts
  - sudo -E sed -i -e '/local.*peer/s/postgres/all/' -e 's/peer\|md5/trust/g' /etc/postgresql/*/main/pg_hba.conf
  - sudo -E sed -i 's/port = 5433/port = 5432/' /etc/postgresql/*/main/postgresql.conf
  - sudo -E service postgresql restart $PGDB

install:
 - pip install -q -r requirements/base.txt
 - pip install -q -r requirements/tests.txt
 - pip install -q django==$DJANGO_VERSION
 - pip install coveralls

script:
 - coverage run manage.py test --settings=test_runner.settings_travis --verbosity=2 --noinput
 - flake8

after_success:
 - coveralls
