language: python
sudo: false
python:
 - "2.7"
 - "3.4"
 - "3.5"
 - "3.6"
env:
 - DJANGO_VERSION=1.9.11
 - DJANGO_VERSION=1.10.5
 - DJANGO_VERSION=1.11.2
install:
 - pip install -q -rrequirements/base.txt
 - pip install -q -rrequirements/tests.txt
 - pip install -q django==$DJANGO_VERSION
 - pip install coveralls
 - pip install coala-bears
before_script:
 - createdb -E UTF-8 dash -U postgres -O $USER
script:
 - coverage run manage.py test --settings=test_runner.settings_travis --verbosity=2 --noinput
 - flake8
 - coala --ci
after_success:
 - coveralls
