# Generated by Django 2.1.5 on 2019-01-10 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20180615_2036'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, help_text='The logo that should be used for this post', null=True, upload_to='images'),
        ),
    ]
