# Generated by Django 2.2.17 on 2021-02-19 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='failedlogin',
            name='username',
            field=models.CharField(max_length=256, null=True),
        ),
    ]
