# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-06-05 08:15
from __future__ import unicode_literals

from django.db import migrations


def remove_anon_user(apps, schema_editor):
    User = apps.get_model('auth', 'User')
    anon = User.objects.filter(username='AnonymousUser').first()
    if anon:
        anon.delete()
        print("Removed anonymous user from database")


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(remove_anon_user)
    ]
